### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdf@asdf.com",
  "password": "asdf123"
}

### find a particular user with a given ID
GET http://localhost:3000/auth/2

### find all users with a given email
GET http://localhost:3000/auth?email=asd2f@asdf.com

### delete a user given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "password": "1234"
}