### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### find a particular user with a given ID
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### sign out
POST http://localhost:3000/auth/signout

### find all users with a given email
GET http://localhost:3000/auth?email=aaaa@aaaaa.com

### delete a user given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "1234"
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get the color
GET http://localhost:3000/auth/colors